/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouRouteImport } from './routes/you'
import { Route as WrapUpRouteImport } from './routes/wrap-up'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EmployerAccessRouteImport } from './routes/employer-access'
import { Route as EmotionTrendsRouteImport } from './routes/emotion-trends'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptTermsRouteImport } from './routes/accept-terms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as FocusAreaNumRouteImport } from './routes/focus-area.$num'
import { Route as DsTextFieldsRouteImport } from './routes/ds.text-fields'
import { Route as DsButtonsRouteImport } from './routes/ds.buttons'

const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const WrapUpRoute = WrapUpRouteImport.update({
  id: '/wrap-up',
  path: '/wrap-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerAccessRoute = EmployerAccessRouteImport.update({
  id: '/employer-access',
  path: '/employer-access',
  getParentRoute: () => rootRouteImport,
} as any)
const EmotionTrendsRoute = EmotionTrendsRouteImport.update({
  id: '/emotion-trends',
  path: '/emotion-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptTermsRoute = AcceptTermsRouteImport.update({
  id: '/accept-terms',
  path: '/accept-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessionsRoute,
} as any)
const FocusAreaNumRoute = FocusAreaNumRouteImport.update({
  id: '/focus-area/$num',
  path: '/focus-area/$num',
  getParentRoute: () => rootRouteImport,
} as any)
const DsTextFieldsRoute = DsTextFieldsRouteImport.update({
  id: '/ds/text-fields',
  path: '/ds/text-fields',
  getParentRoute: () => rootRouteImport,
} as any)
const DsButtonsRoute = DsButtonsRouteImport.update({
  id: '/ds/buttons',
  path: '/ds/buttons',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/emotion-trends': typeof EmotionTrendsRoute
  '/employer-access': typeof EmployerAccessRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/wrap-up': typeof WrapUpRoute
  '/you': typeof YouRoute
  '/ds/buttons': typeof DsButtonsRoute
  '/ds/text-fields': typeof DsTextFieldsRoute
  '/focus-area/$num': typeof FocusAreaNumRoute
  '/sessions/$id': typeof SessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/emotion-trends': typeof EmotionTrendsRoute
  '/employer-access': typeof EmployerAccessRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/wrap-up': typeof WrapUpRoute
  '/you': typeof YouRoute
  '/ds/buttons': typeof DsButtonsRoute
  '/ds/text-fields': typeof DsTextFieldsRoute
  '/focus-area/$num': typeof FocusAreaNumRoute
  '/sessions/$id': typeof SessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/emotion-trends': typeof EmotionTrendsRoute
  '/employer-access': typeof EmployerAccessRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/wrap-up': typeof WrapUpRoute
  '/you': typeof YouRoute
  '/ds/buttons': typeof DsButtonsRoute
  '/ds/text-fields': typeof DsTextFieldsRoute
  '/focus-area/$num': typeof FocusAreaNumRoute
  '/sessions/$id': typeof SessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-terms'
    | '/auth'
    | '/chat'
    | '/emotion-trends'
    | '/employer-access'
    | '/home'
    | '/intro'
    | '/login'
    | '/progress'
    | '/sessions'
    | '/settings'
    | '/tools'
    | '/wrap-up'
    | '/you'
    | '/ds/buttons'
    | '/ds/text-fields'
    | '/focus-area/$num'
    | '/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-terms'
    | '/auth'
    | '/chat'
    | '/emotion-trends'
    | '/employer-access'
    | '/home'
    | '/intro'
    | '/login'
    | '/progress'
    | '/sessions'
    | '/settings'
    | '/tools'
    | '/wrap-up'
    | '/you'
    | '/ds/buttons'
    | '/ds/text-fields'
    | '/focus-area/$num'
    | '/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/accept-terms'
    | '/auth'
    | '/chat'
    | '/emotion-trends'
    | '/employer-access'
    | '/home'
    | '/intro'
    | '/login'
    | '/progress'
    | '/sessions'
    | '/settings'
    | '/tools'
    | '/wrap-up'
    | '/you'
    | '/ds/buttons'
    | '/ds/text-fields'
    | '/focus-area/$num'
    | '/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptTermsRoute: typeof AcceptTermsRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  EmotionTrendsRoute: typeof EmotionTrendsRoute
  EmployerAccessRoute: typeof EmployerAccessRoute
  HomeRoute: typeof HomeRoute
  IntroRoute: typeof IntroRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  WrapUpRoute: typeof WrapUpRoute
  YouRoute: typeof YouRoute
  DsButtonsRoute: typeof DsButtonsRoute
  DsTextFieldsRoute: typeof DsTextFieldsRoute
  FocusAreaNumRoute: typeof FocusAreaNumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrap-up': {
      id: '/wrap-up'
      path: '/wrap-up'
      fullPath: '/wrap-up'
      preLoaderRoute: typeof WrapUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-access': {
      id: '/employer-access'
      path: '/employer-access'
      fullPath: '/employer-access'
      preLoaderRoute: typeof EmployerAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emotion-trends': {
      id: '/emotion-trends'
      path: '/emotion-trends'
      fullPath: '/emotion-trends'
      preLoaderRoute: typeof EmotionTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-terms': {
      id: '/accept-terms'
      path: '/accept-terms'
      fullPath: '/accept-terms'
      preLoaderRoute: typeof AcceptTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/focus-area/$num': {
      id: '/focus-area/$num'
      path: '/focus-area/$num'
      fullPath: '/focus-area/$num'
      preLoaderRoute: typeof FocusAreaNumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/text-fields': {
      id: '/ds/text-fields'
      path: '/ds/text-fields'
      fullPath: '/ds/text-fields'
      preLoaderRoute: typeof DsTextFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/buttons': {
      id: '/ds/buttons'
      path: '/ds/buttons'
      fullPath: '/ds/buttons'
      preLoaderRoute: typeof DsButtonsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SessionsRouteChildren {
  SessionsIdRoute: typeof SessionsIdRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsIdRoute: SessionsIdRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptTermsRoute: AcceptTermsRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  EmotionTrendsRoute: EmotionTrendsRoute,
  EmployerAccessRoute: EmployerAccessRoute,
  HomeRoute: HomeRoute,
  IntroRoute: IntroRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  SessionsRoute: SessionsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  WrapUpRoute: WrapUpRoute,
  YouRoute: YouRoute,
  DsButtonsRoute: DsButtonsRoute,
  DsTextFieldsRoute: DsTextFieldsRoute,
  FocusAreaNumRoute: FocusAreaNumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
