/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouRouteImport } from './routes/you'
import { Route as WrapUpRouteImport } from './routes/wrap-up'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as MeditationRouteImport } from './routes/meditation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GratitudeRouteImport } from './routes/gratitude'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as EmployerAccessRouteImport } from './routes/employer-access'
import { Route as CreatingYourSpaceRouteImport } from './routes/creating-your-space'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnimationSpecsRouteImport } from './routes/animation-specs'
import { Route as AcceptTermsRouteImport } from './routes/accept-terms'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillIdRouteImport } from './routes/skill.$id'
import { Route as SettingsContentPreferencesRouteImport } from './routes/settings_.content-preferences'
import { Route as FocusAreaNumRouteImport } from './routes/focus-area.$num'
import { Route as DsWaveformRouteImport } from './routes/ds.waveform'
import { Route as DsTypographyRouteImport } from './routes/ds.typography'
import { Route as DsToastsRouteImport } from './routes/ds.toasts'
import { Route as DsTextFieldsRouteImport } from './routes/ds.text-fields'
import { Route as DsTagsRouteImport } from './routes/ds.tags'
import { Route as DsSwitchesRouteImport } from './routes/ds.switches'
import { Route as DsSurfaceRouteImport } from './routes/ds.surface'
import { Route as DsSpacingRouteImport } from './routes/ds.spacing'
import { Route as DsSliderRouteImport } from './routes/ds.slider'
import { Route as DsSegmentedToggleRouteImport } from './routes/ds.segmented-toggle'
import { Route as DsRatingScaleRouteImport } from './routes/ds.rating-scale'
import { Route as DsRadialProgressRouteImport } from './routes/ds.radial-progress'
import { Route as DsIconsRouteImport } from './routes/ds.icons'
import { Route as DsDrawerRouteImport } from './routes/ds.drawer'
import { Route as DsDividerRouteImport } from './routes/ds.divider'
import { Route as DsColorsRouteImport } from './routes/ds.colors'
import { Route as DsChatBubblesRouteImport } from './routes/ds.chat-bubbles'
import { Route as DsCardsRouteImport } from './routes/ds.cards'
import { Route as DsCardSuggestionRouteImport } from './routes/ds.card-suggestion'
import { Route as DsButtonsRouteImport } from './routes/ds.buttons'
import { Route as DsBadgeRouteImport } from './routes/ds.badge'
import { Route as DsAvatarsRouteImport } from './routes/ds.avatars'
import { Route as DsAppBarRouteImport } from './routes/ds.app-bar'
import { Route as DsAccordionRouteImport } from './routes/ds.accordion'
import { Route as BookIdRouteImport } from './routes/book.$id'

const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const WrapUpRoute = WrapUpRouteImport.update({
  id: '/wrap-up',
  path: '/wrap-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const MeditationRoute = MeditationRouteImport.update({
  id: '/meditation',
  path: '/meditation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GratitudeRoute = GratitudeRouteImport.update({
  id: '/gratitude',
  path: '/gratitude',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerAccessRoute = EmployerAccessRouteImport.update({
  id: '/employer-access',
  path: '/employer-access',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatingYourSpaceRoute = CreatingYourSpaceRouteImport.update({
  id: '/creating-your-space',
  path: '/creating-your-space',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationSpecsRoute = AnimationSpecsRouteImport.update({
  id: '/animation-specs',
  path: '/animation-specs',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptTermsRoute = AcceptTermsRouteImport.update({
  id: '/accept-terms',
  path: '/accept-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillIdRoute = SkillIdRouteImport.update({
  id: '/skill/$id',
  path: '/skill/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsContentPreferencesRoute =
  SettingsContentPreferencesRouteImport.update({
    id: '/settings_/content-preferences',
    path: '/settings/content-preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const FocusAreaNumRoute = FocusAreaNumRouteImport.update({
  id: '/focus-area/$num',
  path: '/focus-area/$num',
  getParentRoute: () => rootRouteImport,
} as any)
const DsWaveformRoute = DsWaveformRouteImport.update({
  id: '/ds/waveform',
  path: '/ds/waveform',
  getParentRoute: () => rootRouteImport,
} as any)
const DsTypographyRoute = DsTypographyRouteImport.update({
  id: '/ds/typography',
  path: '/ds/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const DsToastsRoute = DsToastsRouteImport.update({
  id: '/ds/toasts',
  path: '/ds/toasts',
  getParentRoute: () => rootRouteImport,
} as any)
const DsTextFieldsRoute = DsTextFieldsRouteImport.update({
  id: '/ds/text-fields',
  path: '/ds/text-fields',
  getParentRoute: () => rootRouteImport,
} as any)
const DsTagsRoute = DsTagsRouteImport.update({
  id: '/ds/tags',
  path: '/ds/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const DsSwitchesRoute = DsSwitchesRouteImport.update({
  id: '/ds/switches',
  path: '/ds/switches',
  getParentRoute: () => rootRouteImport,
} as any)
const DsSurfaceRoute = DsSurfaceRouteImport.update({
  id: '/ds/surface',
  path: '/ds/surface',
  getParentRoute: () => rootRouteImport,
} as any)
const DsSpacingRoute = DsSpacingRouteImport.update({
  id: '/ds/spacing',
  path: '/ds/spacing',
  getParentRoute: () => rootRouteImport,
} as any)
const DsSliderRoute = DsSliderRouteImport.update({
  id: '/ds/slider',
  path: '/ds/slider',
  getParentRoute: () => rootRouteImport,
} as any)
const DsSegmentedToggleRoute = DsSegmentedToggleRouteImport.update({
  id: '/ds/segmented-toggle',
  path: '/ds/segmented-toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const DsRatingScaleRoute = DsRatingScaleRouteImport.update({
  id: '/ds/rating-scale',
  path: '/ds/rating-scale',
  getParentRoute: () => rootRouteImport,
} as any)
const DsRadialProgressRoute = DsRadialProgressRouteImport.update({
  id: '/ds/radial-progress',
  path: '/ds/radial-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const DsIconsRoute = DsIconsRouteImport.update({
  id: '/ds/icons',
  path: '/ds/icons',
  getParentRoute: () => rootRouteImport,
} as any)
const DsDrawerRoute = DsDrawerRouteImport.update({
  id: '/ds/drawer',
  path: '/ds/drawer',
  getParentRoute: () => rootRouteImport,
} as any)
const DsDividerRoute = DsDividerRouteImport.update({
  id: '/ds/divider',
  path: '/ds/divider',
  getParentRoute: () => rootRouteImport,
} as any)
const DsColorsRoute = DsColorsRouteImport.update({
  id: '/ds/colors',
  path: '/ds/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const DsChatBubblesRoute = DsChatBubblesRouteImport.update({
  id: '/ds/chat-bubbles',
  path: '/ds/chat-bubbles',
  getParentRoute: () => rootRouteImport,
} as any)
const DsCardsRoute = DsCardsRouteImport.update({
  id: '/ds/cards',
  path: '/ds/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const DsCardSuggestionRoute = DsCardSuggestionRouteImport.update({
  id: '/ds/card-suggestion',
  path: '/ds/card-suggestion',
  getParentRoute: () => rootRouteImport,
} as any)
const DsButtonsRoute = DsButtonsRouteImport.update({
  id: '/ds/buttons',
  path: '/ds/buttons',
  getParentRoute: () => rootRouteImport,
} as any)
const DsBadgeRoute = DsBadgeRouteImport.update({
  id: '/ds/badge',
  path: '/ds/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const DsAvatarsRoute = DsAvatarsRouteImport.update({
  id: '/ds/avatars',
  path: '/ds/avatars',
  getParentRoute: () => rootRouteImport,
} as any)
const DsAppBarRoute = DsAppBarRouteImport.update({
  id: '/ds/app-bar',
  path: '/ds/app-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const DsAccordionRoute = DsAccordionRouteImport.update({
  id: '/ds/accordion',
  path: '/ds/accordion',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/animation-specs': typeof AnimationSpecsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/creating-your-space': typeof CreatingYourSpaceRoute
  '/employer-access': typeof EmployerAccessRoute
  '/goals': typeof GoalsRoute
  '/gratitude': typeof GratitudeRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/meditation': typeof MeditationRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/wrap-up': typeof WrapUpRoute
  '/you': typeof YouRoute
  '/book/$id': typeof BookIdRoute
  '/ds/accordion': typeof DsAccordionRoute
  '/ds/app-bar': typeof DsAppBarRoute
  '/ds/avatars': typeof DsAvatarsRoute
  '/ds/badge': typeof DsBadgeRoute
  '/ds/buttons': typeof DsButtonsRoute
  '/ds/card-suggestion': typeof DsCardSuggestionRoute
  '/ds/cards': typeof DsCardsRoute
  '/ds/chat-bubbles': typeof DsChatBubblesRoute
  '/ds/colors': typeof DsColorsRoute
  '/ds/divider': typeof DsDividerRoute
  '/ds/drawer': typeof DsDrawerRoute
  '/ds/icons': typeof DsIconsRoute
  '/ds/radial-progress': typeof DsRadialProgressRoute
  '/ds/rating-scale': typeof DsRatingScaleRoute
  '/ds/segmented-toggle': typeof DsSegmentedToggleRoute
  '/ds/slider': typeof DsSliderRoute
  '/ds/spacing': typeof DsSpacingRoute
  '/ds/surface': typeof DsSurfaceRoute
  '/ds/switches': typeof DsSwitchesRoute
  '/ds/tags': typeof DsTagsRoute
  '/ds/text-fields': typeof DsTextFieldsRoute
  '/ds/toasts': typeof DsToastsRoute
  '/ds/typography': typeof DsTypographyRoute
  '/ds/waveform': typeof DsWaveformRoute
  '/focus-area/$num': typeof FocusAreaNumRoute
  '/settings/content-preferences': typeof SettingsContentPreferencesRoute
  '/skill/$id': typeof SkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/animation-specs': typeof AnimationSpecsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/creating-your-space': typeof CreatingYourSpaceRoute
  '/employer-access': typeof EmployerAccessRoute
  '/goals': typeof GoalsRoute
  '/gratitude': typeof GratitudeRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/meditation': typeof MeditationRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/wrap-up': typeof WrapUpRoute
  '/you': typeof YouRoute
  '/book/$id': typeof BookIdRoute
  '/ds/accordion': typeof DsAccordionRoute
  '/ds/app-bar': typeof DsAppBarRoute
  '/ds/avatars': typeof DsAvatarsRoute
  '/ds/badge': typeof DsBadgeRoute
  '/ds/buttons': typeof DsButtonsRoute
  '/ds/card-suggestion': typeof DsCardSuggestionRoute
  '/ds/cards': typeof DsCardsRoute
  '/ds/chat-bubbles': typeof DsChatBubblesRoute
  '/ds/colors': typeof DsColorsRoute
  '/ds/divider': typeof DsDividerRoute
  '/ds/drawer': typeof DsDrawerRoute
  '/ds/icons': typeof DsIconsRoute
  '/ds/radial-progress': typeof DsRadialProgressRoute
  '/ds/rating-scale': typeof DsRatingScaleRoute
  '/ds/segmented-toggle': typeof DsSegmentedToggleRoute
  '/ds/slider': typeof DsSliderRoute
  '/ds/spacing': typeof DsSpacingRoute
  '/ds/surface': typeof DsSurfaceRoute
  '/ds/switches': typeof DsSwitchesRoute
  '/ds/tags': typeof DsTagsRoute
  '/ds/text-fields': typeof DsTextFieldsRoute
  '/ds/toasts': typeof DsToastsRoute
  '/ds/typography': typeof DsTypographyRoute
  '/ds/waveform': typeof DsWaveformRoute
  '/focus-area/$num': typeof FocusAreaNumRoute
  '/settings/content-preferences': typeof SettingsContentPreferencesRoute
  '/skill/$id': typeof SkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/animation-specs': typeof AnimationSpecsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/creating-your-space': typeof CreatingYourSpaceRoute
  '/employer-access': typeof EmployerAccessRoute
  '/goals': typeof GoalsRoute
  '/gratitude': typeof GratitudeRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/login': typeof LoginRoute
  '/meditation': typeof MeditationRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/wrap-up': typeof WrapUpRoute
  '/you': typeof YouRoute
  '/book/$id': typeof BookIdRoute
  '/ds/accordion': typeof DsAccordionRoute
  '/ds/app-bar': typeof DsAppBarRoute
  '/ds/avatars': typeof DsAvatarsRoute
  '/ds/badge': typeof DsBadgeRoute
  '/ds/buttons': typeof DsButtonsRoute
  '/ds/card-suggestion': typeof DsCardSuggestionRoute
  '/ds/cards': typeof DsCardsRoute
  '/ds/chat-bubbles': typeof DsChatBubblesRoute
  '/ds/colors': typeof DsColorsRoute
  '/ds/divider': typeof DsDividerRoute
  '/ds/drawer': typeof DsDrawerRoute
  '/ds/icons': typeof DsIconsRoute
  '/ds/radial-progress': typeof DsRadialProgressRoute
  '/ds/rating-scale': typeof DsRatingScaleRoute
  '/ds/segmented-toggle': typeof DsSegmentedToggleRoute
  '/ds/slider': typeof DsSliderRoute
  '/ds/spacing': typeof DsSpacingRoute
  '/ds/surface': typeof DsSurfaceRoute
  '/ds/switches': typeof DsSwitchesRoute
  '/ds/tags': typeof DsTagsRoute
  '/ds/text-fields': typeof DsTextFieldsRoute
  '/ds/toasts': typeof DsToastsRoute
  '/ds/typography': typeof DsTypographyRoute
  '/ds/waveform': typeof DsWaveformRoute
  '/focus-area/$num': typeof FocusAreaNumRoute
  '/settings_/content-preferences': typeof SettingsContentPreferencesRoute
  '/skill/$id': typeof SkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-terms'
    | '/animation-specs'
    | '/auth'
    | '/chat'
    | '/creating-your-space'
    | '/employer-access'
    | '/goals'
    | '/gratitude'
    | '/home'
    | '/intro'
    | '/login'
    | '/meditation'
    | '/sessions'
    | '/settings'
    | '/tools'
    | '/wrap-up'
    | '/you'
    | '/book/$id'
    | '/ds/accordion'
    | '/ds/app-bar'
    | '/ds/avatars'
    | '/ds/badge'
    | '/ds/buttons'
    | '/ds/card-suggestion'
    | '/ds/cards'
    | '/ds/chat-bubbles'
    | '/ds/colors'
    | '/ds/divider'
    | '/ds/drawer'
    | '/ds/icons'
    | '/ds/radial-progress'
    | '/ds/rating-scale'
    | '/ds/segmented-toggle'
    | '/ds/slider'
    | '/ds/spacing'
    | '/ds/surface'
    | '/ds/switches'
    | '/ds/tags'
    | '/ds/text-fields'
    | '/ds/toasts'
    | '/ds/typography'
    | '/ds/waveform'
    | '/focus-area/$num'
    | '/settings/content-preferences'
    | '/skill/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-terms'
    | '/animation-specs'
    | '/auth'
    | '/chat'
    | '/creating-your-space'
    | '/employer-access'
    | '/goals'
    | '/gratitude'
    | '/home'
    | '/intro'
    | '/login'
    | '/meditation'
    | '/sessions'
    | '/settings'
    | '/tools'
    | '/wrap-up'
    | '/you'
    | '/book/$id'
    | '/ds/accordion'
    | '/ds/app-bar'
    | '/ds/avatars'
    | '/ds/badge'
    | '/ds/buttons'
    | '/ds/card-suggestion'
    | '/ds/cards'
    | '/ds/chat-bubbles'
    | '/ds/colors'
    | '/ds/divider'
    | '/ds/drawer'
    | '/ds/icons'
    | '/ds/radial-progress'
    | '/ds/rating-scale'
    | '/ds/segmented-toggle'
    | '/ds/slider'
    | '/ds/spacing'
    | '/ds/surface'
    | '/ds/switches'
    | '/ds/tags'
    | '/ds/text-fields'
    | '/ds/toasts'
    | '/ds/typography'
    | '/ds/waveform'
    | '/focus-area/$num'
    | '/settings/content-preferences'
    | '/skill/$id'
  id:
    | '__root__'
    | '/'
    | '/accept-terms'
    | '/animation-specs'
    | '/auth'
    | '/chat'
    | '/creating-your-space'
    | '/employer-access'
    | '/goals'
    | '/gratitude'
    | '/home'
    | '/intro'
    | '/login'
    | '/meditation'
    | '/sessions'
    | '/settings'
    | '/tools'
    | '/wrap-up'
    | '/you'
    | '/book/$id'
    | '/ds/accordion'
    | '/ds/app-bar'
    | '/ds/avatars'
    | '/ds/badge'
    | '/ds/buttons'
    | '/ds/card-suggestion'
    | '/ds/cards'
    | '/ds/chat-bubbles'
    | '/ds/colors'
    | '/ds/divider'
    | '/ds/drawer'
    | '/ds/icons'
    | '/ds/radial-progress'
    | '/ds/rating-scale'
    | '/ds/segmented-toggle'
    | '/ds/slider'
    | '/ds/spacing'
    | '/ds/surface'
    | '/ds/switches'
    | '/ds/tags'
    | '/ds/text-fields'
    | '/ds/toasts'
    | '/ds/typography'
    | '/ds/waveform'
    | '/focus-area/$num'
    | '/settings_/content-preferences'
    | '/skill/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptTermsRoute: typeof AcceptTermsRoute
  AnimationSpecsRoute: typeof AnimationSpecsRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CreatingYourSpaceRoute: typeof CreatingYourSpaceRoute
  EmployerAccessRoute: typeof EmployerAccessRoute
  GoalsRoute: typeof GoalsRoute
  GratitudeRoute: typeof GratitudeRoute
  HomeRoute: typeof HomeRoute
  IntroRoute: typeof IntroRoute
  LoginRoute: typeof LoginRoute
  MeditationRoute: typeof MeditationRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  WrapUpRoute: typeof WrapUpRoute
  YouRoute: typeof YouRoute
  BookIdRoute: typeof BookIdRoute
  DsAccordionRoute: typeof DsAccordionRoute
  DsAppBarRoute: typeof DsAppBarRoute
  DsAvatarsRoute: typeof DsAvatarsRoute
  DsBadgeRoute: typeof DsBadgeRoute
  DsButtonsRoute: typeof DsButtonsRoute
  DsCardSuggestionRoute: typeof DsCardSuggestionRoute
  DsCardsRoute: typeof DsCardsRoute
  DsChatBubblesRoute: typeof DsChatBubblesRoute
  DsColorsRoute: typeof DsColorsRoute
  DsDividerRoute: typeof DsDividerRoute
  DsDrawerRoute: typeof DsDrawerRoute
  DsIconsRoute: typeof DsIconsRoute
  DsRadialProgressRoute: typeof DsRadialProgressRoute
  DsRatingScaleRoute: typeof DsRatingScaleRoute
  DsSegmentedToggleRoute: typeof DsSegmentedToggleRoute
  DsSliderRoute: typeof DsSliderRoute
  DsSpacingRoute: typeof DsSpacingRoute
  DsSurfaceRoute: typeof DsSurfaceRoute
  DsSwitchesRoute: typeof DsSwitchesRoute
  DsTagsRoute: typeof DsTagsRoute
  DsTextFieldsRoute: typeof DsTextFieldsRoute
  DsToastsRoute: typeof DsToastsRoute
  DsTypographyRoute: typeof DsTypographyRoute
  DsWaveformRoute: typeof DsWaveformRoute
  FocusAreaNumRoute: typeof FocusAreaNumRoute
  SettingsContentPreferencesRoute: typeof SettingsContentPreferencesRoute
  SkillIdRoute: typeof SkillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrap-up': {
      id: '/wrap-up'
      path: '/wrap-up'
      fullPath: '/wrap-up'
      preLoaderRoute: typeof WrapUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meditation': {
      id: '/meditation'
      path: '/meditation'
      fullPath: '/meditation'
      preLoaderRoute: typeof MeditationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gratitude': {
      id: '/gratitude'
      path: '/gratitude'
      fullPath: '/gratitude'
      preLoaderRoute: typeof GratitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-access': {
      id: '/employer-access'
      path: '/employer-access'
      fullPath: '/employer-access'
      preLoaderRoute: typeof EmployerAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creating-your-space': {
      id: '/creating-your-space'
      path: '/creating-your-space'
      fullPath: '/creating-your-space'
      preLoaderRoute: typeof CreatingYourSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animation-specs': {
      id: '/animation-specs'
      path: '/animation-specs'
      fullPath: '/animation-specs'
      preLoaderRoute: typeof AnimationSpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-terms': {
      id: '/accept-terms'
      path: '/accept-terms'
      fullPath: '/accept-terms'
      preLoaderRoute: typeof AcceptTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill/$id': {
      id: '/skill/$id'
      path: '/skill/$id'
      fullPath: '/skill/$id'
      preLoaderRoute: typeof SkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/content-preferences': {
      id: '/settings_/content-preferences'
      path: '/settings/content-preferences'
      fullPath: '/settings/content-preferences'
      preLoaderRoute: typeof SettingsContentPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus-area/$num': {
      id: '/focus-area/$num'
      path: '/focus-area/$num'
      fullPath: '/focus-area/$num'
      preLoaderRoute: typeof FocusAreaNumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/waveform': {
      id: '/ds/waveform'
      path: '/ds/waveform'
      fullPath: '/ds/waveform'
      preLoaderRoute: typeof DsWaveformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/typography': {
      id: '/ds/typography'
      path: '/ds/typography'
      fullPath: '/ds/typography'
      preLoaderRoute: typeof DsTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/toasts': {
      id: '/ds/toasts'
      path: '/ds/toasts'
      fullPath: '/ds/toasts'
      preLoaderRoute: typeof DsToastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/text-fields': {
      id: '/ds/text-fields'
      path: '/ds/text-fields'
      fullPath: '/ds/text-fields'
      preLoaderRoute: typeof DsTextFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/tags': {
      id: '/ds/tags'
      path: '/ds/tags'
      fullPath: '/ds/tags'
      preLoaderRoute: typeof DsTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/switches': {
      id: '/ds/switches'
      path: '/ds/switches'
      fullPath: '/ds/switches'
      preLoaderRoute: typeof DsSwitchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/surface': {
      id: '/ds/surface'
      path: '/ds/surface'
      fullPath: '/ds/surface'
      preLoaderRoute: typeof DsSurfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/spacing': {
      id: '/ds/spacing'
      path: '/ds/spacing'
      fullPath: '/ds/spacing'
      preLoaderRoute: typeof DsSpacingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/slider': {
      id: '/ds/slider'
      path: '/ds/slider'
      fullPath: '/ds/slider'
      preLoaderRoute: typeof DsSliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/segmented-toggle': {
      id: '/ds/segmented-toggle'
      path: '/ds/segmented-toggle'
      fullPath: '/ds/segmented-toggle'
      preLoaderRoute: typeof DsSegmentedToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/rating-scale': {
      id: '/ds/rating-scale'
      path: '/ds/rating-scale'
      fullPath: '/ds/rating-scale'
      preLoaderRoute: typeof DsRatingScaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/radial-progress': {
      id: '/ds/radial-progress'
      path: '/ds/radial-progress'
      fullPath: '/ds/radial-progress'
      preLoaderRoute: typeof DsRadialProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/icons': {
      id: '/ds/icons'
      path: '/ds/icons'
      fullPath: '/ds/icons'
      preLoaderRoute: typeof DsIconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/drawer': {
      id: '/ds/drawer'
      path: '/ds/drawer'
      fullPath: '/ds/drawer'
      preLoaderRoute: typeof DsDrawerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/divider': {
      id: '/ds/divider'
      path: '/ds/divider'
      fullPath: '/ds/divider'
      preLoaderRoute: typeof DsDividerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/colors': {
      id: '/ds/colors'
      path: '/ds/colors'
      fullPath: '/ds/colors'
      preLoaderRoute: typeof DsColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/chat-bubbles': {
      id: '/ds/chat-bubbles'
      path: '/ds/chat-bubbles'
      fullPath: '/ds/chat-bubbles'
      preLoaderRoute: typeof DsChatBubblesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/cards': {
      id: '/ds/cards'
      path: '/ds/cards'
      fullPath: '/ds/cards'
      preLoaderRoute: typeof DsCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/card-suggestion': {
      id: '/ds/card-suggestion'
      path: '/ds/card-suggestion'
      fullPath: '/ds/card-suggestion'
      preLoaderRoute: typeof DsCardSuggestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/buttons': {
      id: '/ds/buttons'
      path: '/ds/buttons'
      fullPath: '/ds/buttons'
      preLoaderRoute: typeof DsButtonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/badge': {
      id: '/ds/badge'
      path: '/ds/badge'
      fullPath: '/ds/badge'
      preLoaderRoute: typeof DsBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/avatars': {
      id: '/ds/avatars'
      path: '/ds/avatars'
      fullPath: '/ds/avatars'
      preLoaderRoute: typeof DsAvatarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/app-bar': {
      id: '/ds/app-bar'
      path: '/ds/app-bar'
      fullPath: '/ds/app-bar'
      preLoaderRoute: typeof DsAppBarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds/accordion': {
      id: '/ds/accordion'
      path: '/ds/accordion'
      fullPath: '/ds/accordion'
      preLoaderRoute: typeof DsAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptTermsRoute: AcceptTermsRoute,
  AnimationSpecsRoute: AnimationSpecsRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CreatingYourSpaceRoute: CreatingYourSpaceRoute,
  EmployerAccessRoute: EmployerAccessRoute,
  GoalsRoute: GoalsRoute,
  GratitudeRoute: GratitudeRoute,
  HomeRoute: HomeRoute,
  IntroRoute: IntroRoute,
  LoginRoute: LoginRoute,
  MeditationRoute: MeditationRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  WrapUpRoute: WrapUpRoute,
  YouRoute: YouRoute,
  BookIdRoute: BookIdRoute,
  DsAccordionRoute: DsAccordionRoute,
  DsAppBarRoute: DsAppBarRoute,
  DsAvatarsRoute: DsAvatarsRoute,
  DsBadgeRoute: DsBadgeRoute,
  DsButtonsRoute: DsButtonsRoute,
  DsCardSuggestionRoute: DsCardSuggestionRoute,
  DsCardsRoute: DsCardsRoute,
  DsChatBubblesRoute: DsChatBubblesRoute,
  DsColorsRoute: DsColorsRoute,
  DsDividerRoute: DsDividerRoute,
  DsDrawerRoute: DsDrawerRoute,
  DsIconsRoute: DsIconsRoute,
  DsRadialProgressRoute: DsRadialProgressRoute,
  DsRatingScaleRoute: DsRatingScaleRoute,
  DsSegmentedToggleRoute: DsSegmentedToggleRoute,
  DsSliderRoute: DsSliderRoute,
  DsSpacingRoute: DsSpacingRoute,
  DsSurfaceRoute: DsSurfaceRoute,
  DsSwitchesRoute: DsSwitchesRoute,
  DsTagsRoute: DsTagsRoute,
  DsTextFieldsRoute: DsTextFieldsRoute,
  DsToastsRoute: DsToastsRoute,
  DsTypographyRoute: DsTypographyRoute,
  DsWaveformRoute: DsWaveformRoute,
  FocusAreaNumRoute: FocusAreaNumRoute,
  SettingsContentPreferencesRoute: SettingsContentPreferencesRoute,
  SkillIdRoute: SkillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
